In [15]:
import numpy as np
USE_H5PY=False
if USE_H5PY:
    import h5py
    filepath = "./fancy_select.h5"
else:
    import h5pyd as h5py
    filepath = "/home/test_user1/test/fancy_select.h5"

In [16]:
# create a numpy array
arr = np.arange(2*3*4).reshape(2,3,4)
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [17]:
# fancy selection with one coordinate
arr[:, :, [0,1,3]]

array([[[ 0,  1,  3],
        [ 4,  5,  7],
        [ 8,  9, 11]],

       [[12, 13, 15],
        [16, 17, 19],
        [20, 21, 23]]])

In [18]:
# numpy allows multiple coordinate selections also
arr[:,[0,1,2],[1,2,3]]

array([[ 1,  6, 11],
       [13, 18, 23]])

In [19]:
# create a new domain/file
f = h5py.File(filepath, "w")

In [20]:
# create a dataset
dset = f.create_dataset("dset", (5, 1000, 1000), dtype="i4")
dset

<HDF5 dataset "dset": shape (5, 1000, 1000), type "<i4">

In [21]:
# HSDS will auto-chunk the dataset
dset.chunks

(3, 500, 500)

In [22]:
dset.id.id

'd-613c271a-724c7351-aa2e-3f314c-8deb03'

In [23]:
%%time
# write some values to the dataset
for i in range(1000):
    dset[:, i, i] = [i, i*10, i*100, i*1000, i*10000]  # ..

CPU times: user 1.53 s, sys: 2.28 ms, total: 1.53 s
Wall time: 5.23 s


In [24]:
# normal hyperslab selection
dset[:, 444, 444]

array([    444,    4440,   44400,  444000, 4440000], dtype=int32)

In [25]:
# fancyselection with single coordinate (works with h5py and h5pyd)
dset[:, 444, [333,444,555]]

array([[      0,     444,       0],
       [      0,    4440,       0],
       [      0,   44400,       0],
       [      0,  444000,       0],
       [      0, 4440000,       0]], dtype=int32)

In [27]:
# coordinates need to be increasing with h5py (though not with h5pyd)
dset[:, 444, [333, 555, 444]]

array([[      0,       0,     444],
       [      0,       0,    4440],
       [      0,       0,   44400],
       [      0,       0,  444000],
       [      0,       0, 4440000]], dtype=int32)

In [28]:
# fancyselection with multiple coordinates (only works with h5pyd)
dset[:, [1,10,100],[1,10,100]]

array([[      1,      10,     100],
       [     10,     100,    1000],
       [    100,    1000,   10000],
       [   1000,   10000,  100000],
       [  10000,  100000, 1000000]], dtype=int32)

In [29]:
# close file
f.close()